# GOIBIBO INTERNSHIP ASSIGNMENT 1

**Summary:- ** 

**1)** In this notebook, I have used basic Python to first read the text in the provided file and then count the **frequencies of words** present in this text. 

**2)** Having counted the frequencies of all words in the file, I have then showed the **top 10 words** based on the frequencies.

**3)** Also at last, I have treated the words with frequency more than 100 as **stop words.**

### IMPORTING MODULES

In [0]:
# The Natural Language ToolKit.
import nltk   

# data visualisation and manipulation
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style
import seaborn as sns
#configure
# sets matplotlib to inline and displays graphs below the corressponding cell.
% matplotlib inline  
style.use('fivethirtyeight')
sns.set(style='whitegrid',color_codes=True)

# various corpora
from nltk.corpus import movie_reviews as mr  # importing the movie review corpora.

#preprocessing
from nltk.corpus import stopwords  #stopwords
from nltk import word_tokenize,sent_tokenize # tokenizing
from nltk.stem import PorterStemmer,LancasterStemmer  # using the Porter Stemmer and Lancaster Stemmer and others
from nltk.stem.snowball import SnowballStemmer
from nltk.stem import WordNetLemmatizer  # lammatizer from WordNet

# for part-of-speech tagging
from nltk import pos_tag

# for named entity recognition (NER)
from nltk import ne_chunk

# vectorizers for creating the document-term-matrix (DTM)
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

#modelling algos
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.ensemble import GradientBoostingClassifier

#model_selection
from sklearn.model_selection import train_test_split,cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

#evaluation
from sklearn.metrics import accuracy_score,roc_auc_score 
from sklearn.metrics import classification_report
from mlxtend.plotting import plot_confusion_matrix

#preprocessing scikit
from sklearn.preprocessing import MinMaxScaler,StandardScaler,LabelEncoder

 

### READING THE CONTENTS OF THE FILE

I have read the contents of the file by creating the handle and then calling the read method.

In [0]:
f=open("drive/big.txt")
raw_text=f.read()

In [6]:
words=raw_text.split()  
print(len(words)) 

12773


Note that no of total words is 12773.

In [8]:
print(len(set(words))) #  3687 unique words and 12773 total words in file.

3687


Note that no of total unique words is 3687. This is often called as the **Type to Token Ratio (TTR).**

#### Now for now i am simply creating the dictionary where Key is the word itself and Value is the count or frequency. 

****We can also use the Count Vectorizer from scikit. I have shown this approach in the second notebook.****

In [0]:
word_count_dict=dict()
for word in words:
  if word.lower() in word_count_dict:
        word_count_dict[word.lower()] += 1
  else:
        word_count_dict[word] = 1

In [4]:
# word_count_dict

Now I am sorting this dictionary on the basis of the count values.

In [0]:
sorted_word_dict_count={k: v for k, v in sorted(word_count_dict.items(), key=lambda item:item[1], reverse=True)}

In [13]:
sorted_word_dict_count  

{'the': 645,
 'and': 356,
 'of': 346,
 'to': 338,
 'a': 330,
 'in': 210,
 'that': 162,
 'was': 158,
 'he': 154,
 'it': 148,
 'you': 142,
 'his': 140,
 'is': 128,
 'with': 108,
 'my': 108,
 'as': 102,
 'have': 98,
 'for': 87,
 'at': 84,
 'not': 83,
 'be': 82,
 'had': 79,
 'which': 68,
 'she': 67,
 'but': 64,
 'your': 60,
 'me': 57,
 'from': 56,
 'by': 51,
 'said': 51,
 'an': 46,
 'on': 44,
 'very': 44,
 'there': 43,
 'we': 43,
 'this': 41,
 'when': 41,
 'upon': 41,
 'her': 40,
 'been': 40,
 'will': 40,
 'would': 39,
 '"': 39,
 'all': 38,
 'who': 38,
 'into': 37,
 'up': 37,
 'has': 35,
 'could': 34,
 'are': 33,
 'or': 33,
 'if': 33,
 'what': 33,
 'so': 32,
 'am': 32,
 'do': 31,
 'out': 31,
 'one': 31,
 'were': 31,
 'down': 27,
 'little': 26,
 'should': 23,
 'must': 23,
 'how': 22,
 'may': 22,
 'man': 22,
 'some': 21,
 'just': 21,
 'about': 20,
 'own': 19,
 'see': 19,
 'might': 18,
 'more': 18,
 'than': 18,
 'know': 18,
 'good': 18,
 'our': 17,
 'such': 17,
 'they': 17,
 'over': 16,
 'bef

#### This dictionary has the required structure. 

****The key is the word and the value is the count of that word in the file. Also the words are arranged in non increasing order of count.****

## TOP TEN WORDS

Simply slicing the list and showing top 10 words.

In [14]:
sorted_list=list(sorted_word_dict_count.items())
top_ten_words=sorted_list[:10]   
top_ten_words  

[('the', 645),
 ('and', 356),
 ('of', 346),
 ('to', 338),
 ('a', 330),
 ('in', 210),
 ('that', 162),
 ('was', 158),
 ('he', 154),
 ('it', 148)]

## REMOVING STOPWORDS

In this notebook I have just simply treated words occuring more than 100 times (arbitarily) as stopwords. We can use stopwords from scikit as well which I have shown in the second notebook.

In [ ]:
#removing stopwords.
for tup in sorted_list:
  if tup[1]<=100:
     words_wo_stop_words.append(tup)

In [16]:
words_wo_stop_words

[('have', 98),
 ('for', 87),
 ('at', 84),
 ('not', 83),
 ('be', 82),
 ('had', 79),
 ('which', 68),
 ('she', 67),
 ('but', 64),
 ('your', 60),
 ('me', 57),
 ('from', 56),
 ('by', 51),
 ('said', 51),
 ('an', 46),
 ('on', 44),
 ('very', 44),
 ('there', 43),
 ('we', 43),
 ('this', 41),
 ('when', 41),
 ('upon', 41),
 ('her', 40),
 ('been', 40),
 ('will', 40),
 ('would', 39),
 ('"', 39),
 ('all', 38),
 ('who', 38),
 ('into', 37),
 ('up', 37),
 ('has', 35),
 ('could', 34),
 ('are', 33),
 ('or', 33),
 ('if', 33),
 ('what', 33),
 ('so', 32),
 ('am', 32),
 ('do', 31),
 ('out', 31),
 ('one', 31),
 ('were', 31),
 ('down', 27),
 ('little', 26),
 ('should', 23),
 ('must', 23),
 ('how', 22),
 ('may', 22),
 ('man', 22),
 ('some', 21),
 ('just', 21),
 ('about', 20),
 ('own', 19),
 ('see', 19),
 ('might', 18),
 ('more', 18),
 ('than', 18),
 ('know', 18),
 ('good', 18),
 ('our', 17),
 ('such', 17),
 ('they', 17),
 ('over', 16),
 ('before', 16),
 ('him', 16),
 ('most', 16),
 ('after', 16),
 ('other', 15),